### ISSUE TITLE
How to pick sound quality?

### ISSUE THREAD

**Issue by jacksight** [FuNk-y0u/boltz#2]
I've looked through the code, but I'm wondering how to change the download quality/format of the music?

**Comment by robesckey2k6** [comment]
[https://github.com/FuNk-y0u/boltz/blob/main/utils.py](url)
in utils.py a function called **"generate_ytdl_opts"**,
"generate_ytdl_opts" function :
`
generate_ytdl_opts(_out_template:str,
                       _post_processor:[dict],
                       _track_name:str,
                       _track_artist:str,
                       _track_album:str) -> dict`

theres a dict called **"mp3_pp_opts"** in the function where you can change the quality and codec!

"mp3_pp_opts" dict here:
`
 mp3_pp_opts = {
        "key": "FFmpegExtractAudio",
        "preferredcodec": "[your codec here]",
        "preferredquality": "[quality here]",
    }
`

Sorry for inconvenience, I will add an option to change the codec and quality through the boltz api itself!
